insert into parc (fid, nume, suprafata) values ('1', 'Parcul National Domogled Valea Cernei', '61200');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('1', 'Lacul Prisaca', '78', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('2', 'Lacul Iovan', '290', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('3', 'Raul Cerna Sector 1', '2', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('4', 'Raul Cerna Sector 2', '3', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('5', 'Raul Cerna Sector 3', '6', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('6', 'Raul Cerna Sector 4', '2', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('7', 'Raul Cerna Sector 5', '8', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('8', 'Raul Cerna Sector 6', '5', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('9', 'Raul Cerna Sector 7', '3', '1');
insert into unitati_acvatice (id, nume, suprafata, fid_parc) values ('10', 'Raul Cerna Sector 8', '7', '1');
insert into tip_ua (id,tip, id_unitati_acvatice) values ('1', 'Lac','1');
insert into tip_ua (id,tip, id_unitati_acvatice) values ('2', 'Lac','2');
insert into tip_ua (id,tip, id_unitati_acvatice) values ('3', 'Rau','3');
insert into tip_ua (id,tip, id_unitati_acvatice) values ('4', 'Rau','4');
insert into tip_ua (id,tip, id_unitati_acvatice) values ('5', 'Rau','5');
insert into tip_ua (id,tip, id_unitati_acvatice) values ('1', 'Lac','1');